### ISSUE TITLE
JSONField Error

### ISSUE THREAD

**Issue by earthpyy** [C0D1UM/django-secured-fields#46]
```
Found 88 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..............................F......................FF............F....................
======================================================================
FAIL: test_simple (main.tests.test_fields.JSONFieldTestCase.test_simple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/django-secured-fields/test_secured_fields/main/tests/test_fields.py", line 381, in test_simple
    self.create_and_assert({'name': 'John Doe'})
  File "/django-secured-fields/test_secured_fields/main/tests/test_fields.py", line 91, in create_and_assert
    self.assertEqual(self.model.field, assert_value if assert_value is not test_utils.NoValue else create_value)
AssertionError: '\'{"name": "John Doe"}\'' != {'name': 'John Doe'}

======================================================================
FAIL: test_simple (main.tests.test_fields.SearchableJSONFieldTestCase.test_simple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/django-secured-fields/test_secured_fields/main/tests/test_fields.py", line 381, in test_simple
    self.create_and_assert({'name': 'John Doe'})
  File "/django-secured-fields/test_secured_fields/main/tests/test_fields.py", line 91, in create_and_assert
    self.assertEqual(self.model.field, assert_value if assert_value is not test_utils.NoValue else create_value)
AssertionError: '\'{"name": "John Doe"}\'' != {'name': 'John Doe'}

======================================================================
FAIL: test_with_salt (main.tests.test_fields.SearchableJSONFieldTestCase.test_with_salt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/redacted/Library/Caches/pypoetry/virtualenvs/django-secured-fields-3DI1WX7i-py3.12/lib/python3.12/site-packages/django/test/utils.py", line 461, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/django-secured-fields/test_secured_fields/main/tests/test_fields.py", line 391, in test_with_salt
    self.create_and_assert({'name': 'John Doe'})
  File "/django-secured-fields/test_secured_fields/main/tests/test_fields.py", line 91, in create_and_assert
    self.assertEqual(self.model.field, assert_value if assert_value is not test_utils.NoValue else create_value)
AssertionError: '\'{"name": "John Doe"}\'' != {'name': 'John Doe'}

======================================================================
FAIL: test_json_field (main.tests.test_lookups.EncryptedExactLookupTestCase.test_json_field)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/django-secured-fields/test_secured_fields/main/tests/test_lookups.py", line 58, in test_json_field
    self.create_and_assert(models.SearchableJSONFieldModel, {'name': 'John Doe'})
  File "/django-secured-fields/test_secured_fields/main/tests/test_lookups.py", line 24, in create_and_assert
    self.assertIsNotNone(model)
AssertionError: unexpectedly None

----------------------------------------------------------------------
Ran 88 tests in 1.001s

FAILED (failures=4)
Destroying test database for alias 'default'...
```

**Comment by earthpyy** [comment]
Tests are passed now.
